name: Deploy to AWS S3

on:
  workflow_run:
    workflows: ["test"]  # This refers to your test.yml workflow
    types: [completed]
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Only deploy if tests passed
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    - name: Sync to S3
      run: |
        aws s3 sync . s3://silas-portfolio --delete --exclude ".git/*" --exclude ".github/*" --exclude "README.md"
        
    - name: Deployment success
      run: |
        echo "🚀 Website deployed successfully!"
        echo "📍 AWS URL: http://silas-portfolio.s3-website-us-east-1.amazonaws.com"
        echo "✅ Tests passed and deployment completed"
