name: Deploy to AWS S3

on:
  workflow_run:
    workflows: ["test"]
    types: [completed]
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Only deploy if tests passed
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    - name: Deploy to S3
      run: |
        echo "🚀 Starting deployment to AWS S3..."
        aws s3 sync . s3://silas-portfolio \
          --delete \
          --exclude ".git/*" \
          --exclude ".github/*" \
          --exclude "README.md" \
          --exclude "*.md" \
          --exclude ".gitignore"
          
    - name: Verify deployment
      run: |
        echo "✅ Deployment completed successfully!"
        echo "🌐 Website URL: http://silas-portfolio.s3-website-us-east-1.amazonaws.com"
        echo "📊 GitHub Pages: https://yourusername.github.io/repository-name"
        
    - name: Optional CloudFront invalidation
      run: |
        # Uncomment if you set up CloudFront
        # aws cloudfront create-invalidation --distribution-id YOUR_DISTRIBUTION_ID --paths "/*"
        echo "💡 Tip: Set up CloudFront for HTTPS and global CDN"